#!/bin/bash

# This script prints your Slurm job history using sacct and sinfo.

print_help() {
  echo -e "\nNAME"
  echo -e "\tshistory - show Slurm job history\n"
  echo -e "USAGE"
  echo -e "\tshistory [-u username | -d days | -a | -c | -g | -j | -n | -v | -w] [-h]\n"
  echo -e "OPTIONS"
  echo -e "\t-a,--all"
  echo -e "\t\tShow all intermediate job steps."
  echo -e "\t-c,--concise"
  echo -e "\t\tDisplay concise output by using fewer columns."
  echo -e "\t-d,--days"
  echo -e "\t\tShow jobs over this many previous days from now (default: 7)."
  echo -e "\t-g,--gpus"
  echo -e "\t\tShow number of allocated GPUs per node."
  echo -e "\t-j,--join"
  echo -e "\t\tJoin the nodelist to the node features (single-node jobs only). This"
  echo -e "\t\tis useful on Della to see which generation of Intel CPUs were used. Only"
  echo -e "\t\tcompatible with the -u and -d options."
  echo -e "\t-n,--nodelist"
  echo -e "\t\tShow the nodelist for each job."
  echo -e "\t-u,--username"
  echo -e "\t\tSpecify the NetID of a user (default: you).\n"
  echo -e "\t-v,--verbose"
  echo -e "\t\tShow the sacct command that was used to generate the output.\n"
  echo -e "\t-w,--workdir"
  echo -e "\t\tShow the working directoring for each job."
  echo -e "EXAMPLES"
  echo -e "\tShow your job history over the last 7 days:"
  echo -e "\t\t$ shistory\n"
  echo -e "\tShow your job history over the last 3 days with extra info about GPU allocations:"
  echo -e "\t\t$ shistory -d 3 -g\n"
  echo -e "\tShow your job history over the last 7 days including all job steps:"
  echo -e "\t\t$ shistory -a\n"
  echo -e "\tShow the job history of aturing over the last 7 days:"
  echo -e "\t\t$ shistory -u aturing\n"
}

# set default values
username="$USER"
days=7
show_all_steps=false
concise=false
gpus=false
workdir=false
nodelist=false
show_command=false
features=false

# parse command-line arguments
while [[ "$#" -gt 0 ]]
do
  case $1 in
    -h|--help)
      print_help
      exit
      ;;
    -u|--username)
      username="$2";
      shift;
      ;;
    -d|--days)
      days="$2";
      shift;
      ;;
    -a|--all)
      show_all_steps=true;
      ;;
    -c|--concise)
      concise=true;
      ;;
    -g|--gpus)
      gpus=true;
      ;;
    -v|--verbose)
      show_command=true;
      ;;
    -w|--workdir)
      workdir=true;
      ;;
    -n|--nodelist)
      nodelist=true;
      ;;
    -j|--join)
      features=true;
      ;;
  esac
  shift
done

# set columns to show
if ${concise}; then
  FMT=jobid%12,state%11,start,elapsed%11,nnodes%6,ncpus%5,jobname%8;
else
  FMT=jobid%16,state%11,start,elapsed%11,timelimit%11,nnodes%6,ncpus%5,reqmem%10,partition,jobname%8;
fi

# append to FMT
if ${gpus}; then
  FMT=${FMT},alloctres%50
fi
if ${nodelist}; then
  FMT=${FMT},nodelist%50
fi
if ${workdir}; then
  FMT=${FMT},workdir%75
fi

start_date=$(date -d"${days} days ago" +%D);

# features
if ${features}; then
  FMT=nodelist%25,jobid%20,nnodes,state,start,jobname,alloctres%50;
  echo "  JobID    Node    Features   State   Start   JobName    AllocTRES"
  echo "------------------------------------------------------------"
  join -j 1 -o "1.2,1.1,2.2,1.4,1.5,1.6,1.7" \
  <(sacct -X -n -u ${username} -S ${start_date} -o ${FMT} | grep " 1 " | grep -v "None assigned" | uniq | sort -k 1b,1) \
  <(sinfo --Node -o "%25n %f" | grep -v "HOSTNAMES" | uniq | sort -k 1b,1) | sort | tr " " '\t' | sed 's/billing=[0-9]\+,//'
  exit
fi

# use sacct to print the job history
if ${show_all_steps}; then
    sacct -u ${username} -S ${start_date} -o ${FMT};
    if ${show_command}; then
        echo -e "\nThe output above came from this command:"
        echo "  sacct -u ${username} -S ${start_date} -o ${FMT}"
    fi
else
    sacct -X -u ${username} -S ${start_date} -o ${FMT};
    if ${show_command}; then
        echo -e "\nThe output above came from this command:"
        echo "  sacct -X -u ${username} -S ${start_date} -o ${FMT}"
    fi
fi
