#!/bin/bash

# This script prints your Slurm job history using sacct.

print_help() {
  echo -e "\nNAME"
  echo -e "\tshistory - show Slurm job history\n"
  echo -e "USAGE"
  echo -e "\tshistory [-u username | -d days | -g | -a] [-h]\n"
  echo -e "OPTIONS"
  echo -e "\t-a,--all"
  echo -e "\t\tShow all intermediate job steps (default: false)"
  echo -e "\t-d,--days"
  echo -e "\t\tShow jobs over this many previous days from now (default: 7)"
  echo -e "\t-g,--gpus"
  echo -e "\t\tShow number of allocated GPUs per node (default: false)"
  echo -e "\t-u,--username"
  echo -e "\t\tSpecify the NetID of a user (default: you)\n"
  echo -e "EXAMPLES"
  echo -e "\tShow your job history over the last 7 days:"
  echo -e "\t\t$ shistory\n"
  echo -e "\tShow your job history over the last 3 days including GPU allocations:"
  echo -e "\t\t$ shistory -d 3 -g\n"
  echo -e "\tShow your job history over the last 7 days including all job steps:"
  echo -e "\t\t$ shistory -a\n"
  echo -e "\tShow the job history of aturing over the last 7 days:"
  echo -e "\t\t$ shistory -u aturing\n"
}

# set default values
username="$USER"
days=7
show_all_steps=false
gpus=false

# parse command-line arguments
while [[ "$#" -gt 0 ]]
do
  case $1 in
    -h|--help)
      print_help
      exit
      ;;
    -u|--username)
      username="$2";
      shift;
      ;;
    -d|--days)
      days="$2";
      shift;
      ;;
    -a|--all)
      show_all_steps=true;
      ;;
    -g|--gpus)
      gpus=true;
      ;;
  esac
  shift
done

# set columns to show
if ${gpus}; then
  FMT=jobid%16,state,start,elapsed%11,timelimit%11,ncpus%5,nnodes%6,reqmem%10,alloctres%50,partition,jobname%8;
else
  FMT=jobid%16,state,start,elapsed%11,timelimit%11,ncpus%5,nnodes%6,reqmem%10,partition,jobname%8;
fi

# compute starting date of time window
seconds=$(($days * 24 * 60 * 60));
now=$(date +%s);
minusdays=$((now - $seconds));
startdate=$(date --date=@$minusdays +'%Y-%m-%d');

# use sacct to print the job history
if ${show_all_steps}; then
    sacct -u ${username} -S ${startdate} -o ${FMT};
else
    sacct -u ${username} -S ${startdate} -o ${FMT} | grep -v -E '[0-9_]{4}\.(ex|ba|in)|[0-9_]{4}\.[0-9]{1,} ';
fi
